//Método dinámico para generar el contenido del footer
function fillFooter() {
    const FOOTER = document.querySelector("footer");
    FOOTER.id = "nosik-footer";
    const LOGO = document.createElement("img");
    LOGO.id = "nosik-footer-logo";
    LOGO.src = "../img/nosik_logo_white.svg";
    FOOTER.appendChild(LOGO);
    const CONTACT_DIV = document.createElement("div");
    CONTACT_DIV.setAttribute("class","nosik-column-div");
    FOOTER.appendChild(CONTACT_DIV);
    const TITLE_CONTACT = document.createElement("h3");
    TITLE_CONTACT.textContent = "Contacto";
    TITLE_CONTACT.classList.add("nosik-title-column");
    CONTACT_DIV.appendChild(TITLE_CONTACT);
    const P1 = document.createElement("p");
    P1.textContent = "¿Tienes una idea de obra o proyecto?";
    P1.classList.add("nosik-p-contact");
    CONTACT_DIV.appendChild(P1);
    const P2 = document.createElement("p");
    P2.textContent = "¿Tienes una marca y te gustaría colaborar conmigo?";
    P2.classList.add("nosik-p-contact");
    CONTACT_DIV.appendChild(P2);
    const RRSS_DIV = document.createElement("div");
    RRSS_DIV.id = "nosik-rrss-div";
    CONTACT_DIV.appendChild(RRSS_DIV);
    const P3 = document.createElement("p");
    P3.textContent = "Escríbeme.";
    P3.classList.add("nosik-p-rrss");
    RRSS_DIV.appendChild(P3);
    const MAIL_DIV = document.createElement("div");
    MAIL_DIV.setAttribute("class", "nosik-single-rrss-div");
    RRSS_DIV.appendChild(MAIL_DIV);
    const MAIL_ICON = document.createElement("img");
    MAIL_ICON.id = "nosik-mail-icon";
    MAIL_ICON.src = "../img/email_icon.svg";
    MAIL_DIV.appendChild(MAIL_ICON);
    const EMAIL_A = document.createElement("a");
    EMAIL_A.setAttribute("class", "nosik-rrss-a");
    EMAIL_A.href = "mailto:g.nosik1999@gmail.com";
    EMAIL_A.textContent = "g.nosik1999@gmail.com";
    MAIL_DIV.appendChild(EMAIL_A);
    const INSTAGRAM_DIV = document.createElement("div");
    INSTAGRAM_DIV.setAttribute("class", "nosik-single-rrss-div");
    RRSS_DIV.appendChild(INSTAGRAM_DIV);
    const INSTAGRAM_ICON = document.createElement("img");
    INSTAGRAM_ICON.id = "nosik-mail-icon";
    INSTAGRAM_ICON.src = "../img/instagram_icon.svg";
    INSTAGRAM_DIV.appendChild(INSTAGRAM_ICON);
    const INSTAGRAM_A = document.createElement("a");
    INSTAGRAM_A.setAttribute("class", "nosik-rrss-a");
    INSTAGRAM_A.setAttribute("target", "blank");
    INSTAGRAM_A.href = "https://www.instagram.com/nosikart1/";
    INSTAGRAM_A.textContent = "nosikart1";
    INSTAGRAM_DIV.appendChild(INSTAGRAM_A);
    const TIKTOK_DIV = document.createElement("div");
    TIKTOK_DIV.setAttribute("class", "nosik-single-rrss-div");
    RRSS_DIV.appendChild(TIKTOK_DIV);
    const TIKTOK_ICON = document.createElement("img");
    TIKTOK_ICON.id = "nosik-mail-icon";
    TIKTOK_ICON.src = "../img/TIKTOK_icon.svg";
    TIKTOK_DIV.appendChild(TIKTOK_ICON);
    const TIKTOK_A = document.createElement("a");
    TIKTOK_A.setAttribute("class", "nosik-rrss-a");
    TIKTOK_A.setAttribute("target", "blank");
    TIKTOK_A.href = "https://www.tiktok.com/@nosikart1?_t=8hka0BNSega&_r=1";
    TIKTOK_A.textContent = "nosikart1";
    TIKTOK_DIV.appendChild(TIKTOK_A);
    const PAYMENT_DIV = document.createElement("div");
    PAYMENT_DIV.setAttribute("class", "nosik-column-div");
    FOOTER.appendChild(PAYMENT_DIV);
    const PAYMENT_TITLE = document.createElement("h3");
    PAYMENT_TITLE.textContent = "Métodos de pago";
    PAYMENT_TITLE.classList.add("nosik-title-column");
    PAYMENT_DIV.appendChild(PAYMENT_TITLE);
    const PAYMENT_IMG = document.createElement("img");
    PAYMENT_IMG.id = "nosik-payment-img";
    PAYMENT_IMG.src = "../img/payments_methods.png";
    PAYMENT_DIV.appendChild(PAYMENT_IMG);
}
fillFooter();